theme: jekyll-theme-minimal
title: McGill's Initiative in Computational Medicine
description: Our organization aims to advance biomedical research at McGill by providing researchers with workshops and boot camps on crucial skills and tools for Bioinformatics research. Our courses cover a range of skill levels to ensure all researchers can use our platform to advance their research. 
